In [1]:
import pandas as pd
# Code to read csv file into Colaboratory:

Load Census Demographics Data by Tract and remove margin of error data, can be replicable with other state data. Dataset comes from Census [S0701 GEOGRAPHIC MOBILITY BY SELECTED CHARACTERISTICS IN THE UNITED STATES. ](https://data.census.gov/cedsci/table?q=S0701%20%20GEOGRAPHIC%20MOBILITY%20BY%20SELECTED%20CHARACTERISTICS%20IN%20THE%20UNITED%20STATES&g=0400000US27%241400000&tid=ACSST5Y2020.S0701)

In [3]:
df = pd.read_csv("/Demographicstract.csv")
df = df.loc[:, ~df.columns.str.endswith('M')]
df = df[df.columns[~df.columns.str.endswith('M')]]
df = df.loc[:, ~df.columns.str.startswith('S0701_C02')]
df = df[df.columns[~df.columns.str.startswith('S0701_C02')]]
df = df.loc[:, ~df.columns.str.startswith('S0701_C03')]
df = df[df.columns[~df.columns.str.startswith('S0701_C03')]]
df = df.loc[:, ~df.columns.str.startswith('S0701_C04')]
df = df[df.columns[~df.columns.str.startswith('S0701_C04')]]
df = df.loc[:, ~df.columns.str.startswith('S0701_C05')]
df = df[df.columns[~df.columns.str.startswith('S0701_C05')]]
new_header = df.iloc[0] #grab the first row for the header
df = df[1:] #take the data less the header row
df.columns = new_header #set the header row as the df header

FileNotFoundError: [Errno 2] No such file or directory: '/Demographicstract.csv'

In [ ]:
df

,id,Geographic Area Name,Estimate!!Total!!Population 1 year and over,Estimate!!Total!!Population 1 year and over!!AGE!!1 to 4 years,Estimate!!Total!!Population 1 year and over!!AGE!!5 to 17 years,Estimate!!Total!!Population 1 year and over!!AGE!!18 to 24 years,Estimate!!Total!!Population 1 year and over!!AGE!!25 to 34 years,Estimate!!Total!!Population 1 year and over!!AGE!!35 to 44 years,Estimate!!Total!!Population 1 year and over!!AGE!!45 to 54 years,Estimate!!Total!!Population 1 year and over!!AGE!!55 to 64 years,...,"Estimate!!Total!!INDIVIDUAL INCOME IN THE PAST 12 MONTHS (IN 2020 INFLATION-ADJUSTED DOLLARS)!!Population 15 years and over!!$75,000 or more",Estimate!!Total!!INDIVIDUAL INCOME IN THE PAST 12 MONTHS (IN 2020 INFLATION-ADJUSTED DOLLARS)!!Population 15 years and over!!Median income (dollars),Estimate!!Total!!POVERTY STATUS IN THE PAST 12 MONTHS!!Population 1 year and over for whom poverty status is determined,Estimate!!Total!!POVERTY STATUS IN THE PAST 12 MONTHS!!Population 1 year and over for whom poverty status is determined!!Below 100 percent of the poverty level,Estimate!!Total!!POVERTY STATUS IN THE PAST 12 MONTHS!!Population 1 year and over for whom poverty status is determined!!100 to 149 percent of the poverty level,Estimate!!Total!!POVERTY STATUS IN THE PAST 12 MONTHS!!Population 1 year and over for whom poverty status is determined!!At or above 150 percent of the poverty level,Estimate!!Total!!HOUSING TENURE!!Population 1 year and over in housing units,Estimate!!Total!!HOUSING TENURE!!Population 1 year and over in housing units!!Householder lived in owner-occupied housing units,Estimate!!Total!!HOUSING TENURE!!Population 1 year and over in housing units!!Householder lived in renter-occupied housing units,Estimate!!Total!!PERCENT ALLOCATED!!Residence 1 year ago
1,1400000US27001770100,"Census Tract 7701, Aitkin County, Minnesota",2247,66,198,98,163,162,249,556,...,182,28170,2247,283,228,1736,2247,2045,202,6.6
2,1400000US27001770200,"Census Tract 7702, Aitkin County, Minnesota",2246,92,349,116,150,209,226,472,...,122,28268,2226,277,248,1701,2234,1763,471,5.3
3,1400000US27001770300,"Census Tract 7703, Aitkin County, Minnesota",3422,88,637,287,331,312,403,359,...,244,26203,3234,503,429,2302,3192,2388,804,6.5
4,1400000US27001770401,"Census Tract 7704.01, Aitkin County, Minnesota",1323,36,151,51,90,77,167,285,...,193,32819,1323,100,133,1090,1323,1164,159,4.2
5,1400000US27001770402,"Census Tract 7704.02, Aitkin County, Minnesota",1651,59,254,123,151,132,174,281,...,78,23681,1648,264,188,1196,1651,1193,458,4.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1502,1400000US27173970100,"Census Tract 9701, Yellow Medicine County, Min...",3012,134,554,218,332,395,350,488,...,309,34104,2973,337,519,2117,2936,2219,717,6.5
1503,1400000US27173970200,"Census Tract 9702, Yellow Medicine County, Min...",2194,82,392,140,169,223,238,334,...,145,31011,2142,176,160,1806,2089,1856,233,5.1
1504,1400000US27173970300,"Census Tract 9703, Yellow Medicine County, Min...",2326,126,394,146,347,204,231,359,...,240,33864,2265,156,128,1981,2277,1919,358,7.8
1505,1400000US27173970400,"Census Tract 9704, Yellow Medicine County, Min...",2131,147,322,207,277,236,281,322,...,144,31632,2123,209,115,1799,2127,1814,313,3.6
1506,0400000US27,Minnesota,5535623,286561,948180,498444,760033,710985,692277,751567,...,809356,37320,5414031,503115,355616,4555300,5405156,4093039,1312117,7.2